[package]
name = "curseforge-api-wrapper"
version = "0.1.0"
edition = "2024"
authors = ["STierProgrammer"]
description = "Rust wrapper for the official Curseforge API"
repository = "https://github.com/SynthLauncher/curseforge-api-wrapper"
license = "MIT"

[dependencies]
